name: binstate
description: A Dart library for efficient binary serialization of state objects.
version: 1.0.1
repository: https://github.com/putraxor/binstate

environment:
  sdk: ^3.8.1

dependencies:
  archive: ^4.0.7

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
